from __future__ import annotations

from dataclasses import dataclass
from datetime import date, datetime
from typing import Any

import httpx
import pandas as pd

from backend.data.adapters.base import AdapterFetchResult, DataAdapter, iso_timestamp, parse_as_of_date
from backend.data.adapters.edgar_adapter import SEC_HEADERS
from backend.data.adapters.yfinance_adapter import YFinanceAdapter


QUARTERLY_FORMS = {"10-Q", "10-Q/A", "10-K", "10-K/A"}
INSTANT_FORMS = {"10-Q", "10-Q/A", "10-K", "10-K/A", "8-K", "8-K/A"}
SNAPSHOT_CACHE_VERSION = "v2"


@dataclass(slots=True)
class FactPoint:
    value: float
    filed: date
    end: date
    start: date | None
    form: str
    fp: str
    frame: str


class SecCompanyFactsAdapter(DataAdapter):
    source_name = "sec_companyfacts"
    default_ttl_minutes = 1440
    supports_point_in_time = True

    async def fetch(self, ticker: str, as_of_datetime: str | None = None) -> AdapterFetchResult:
        payload = await self.get_company_snapshot(ticker, as_of_datetime=as_of_datetime)
        return AdapterFetchResult(
            source=self.source_name,
            fetched_at=iso_timestamp(as_of_datetime),
            payload=payload,
            point_in_time_supported=True,
        )

    async def get_company_snapshot(self, ticker: str, as_of_datetime: str | None = None) -> dict[str, float | int | str | None]:
        as_of = parse_as_of_date(as_of_datetime)
        # Version the derived snapshot cache so historical replay never reuses
        # metrics generated by an older reconstruction formula.
        cache_key = self._cache_key("snapshot", SNAPSHOT_CACHE_VERSION, ticker.upper(), as_of.isoformat())
        cached = await self.cache.get(cache_key)
        if isinstance(cached, dict):
            return cached

        company = await self.lookup_company(ticker)
        if not company:
            return {}
        cik = company["cik"]
        company_name = company["name"]

        try:
            payload = await self._get_json(
                f"https://data.sec.gov/api/xbrl/companyfacts/CIK{cik}.json",
                headers=SEC_HEADERS,
                cache_key=self._cache_key("companyfacts", cik),
                ttl_minutes=self.default_ttl_minutes,
                rate_limit_name="edgar",
                timeout=25.0,
            )
        except httpx.HTTPError:
            return {}

        snapshot = await self._build_snapshot(
            ticker=ticker.upper(),
            company_name=company_name,
            payload=payload if isinstance(payload, dict) else {},
            as_of=as_of,
            as_of_datetime=as_of_datetime,
        )
        await self.cache.set(cache_key, snapshot, ttl_minutes=self.default_ttl_minutes, source=self.source_name)
        return snapshot

    async def lookup_company(self, ticker: str) -> dict[str, str] | None:
        try:
            payload = await self._get_json(
                "https://www.sec.gov/files/company_tickers.json",
                headers=SEC_HEADERS,
                cache_key=self._cache_key("company-tickers"),
                ttl_minutes=10080,
                rate_limit_name="edgar",
            )
        except httpx.HTTPError:
            return None

        normalized = ticker.strip().upper()
        for item in payload.values():
            if str(item.get("ticker", "")).upper() != normalized:
                continue
            return {
                "cik": str(item.get("cik_str", "")).zfill(10),
                "name": str(item.get("title", "")).strip() or normalized,
            }
        return None

    async def _build_snapshot(
        self,
        *,
        ticker: str,
        company_name: str,
        payload: dict[str, Any],
        as_of: date,
        as_of_datetime: str | None,
    ) -> dict[str, float | int | str | None]:
        revenues = self._quarterly_series(
            payload,
            as_of,
            concepts=["RevenueFromContractWithCustomerExcludingAssessedTax", "SalesRevenueNet", "Revenues"],
        )
        gross_profit = self._quarterly_series(payload, as_of, concepts=["GrossProfit"])
        operating_income = self._quarterly_series(payload, as_of, concepts=["OperatingIncomeLoss"])
        net_income = self._quarterly_series(payload, as_of, concepts=["NetIncomeLoss", "ProfitLoss"])
        operating_cash_flow = self._quarterly_series(
            payload,
            as_of,
            concepts=["NetCashProvidedByUsedInOperatingActivities"],
        )
        capex = self._quarterly_series(
            payload,
            as_of,
            concepts=["PaymentsToAcquirePropertyPlantAndEquipment"],
        )
        depreciation = self._quarterly_series(
            payload,
            as_of,
            concepts=["DepreciationDepletionAndAmortization"],
        )
        dividends_per_share = self._quarterly_series(
            payload,
            as_of,
            concepts=["CommonStockDividendsPerShareDeclared"],
            units={"USD/shares"},
        )
        shares = self._instant_series(
            payload,
            as_of,
            concepts=["EntityCommonStockSharesOutstanding", "CommonStockSharesOutstanding"],
            units={"shares"},
        )
        assets = self._latest_instant(payload, as_of, concepts=["Assets"])
        current_assets = self._latest_instant(payload, as_of, concepts=["AssetsCurrent"])
        liabilities_current = self._latest_instant(payload, as_of, concepts=["LiabilitiesCurrent"])
        equity = self._latest_instant(
            payload,
            as_of,
            concepts=["StockholdersEquity", "StockholdersEquityIncludingPortionAttributableToNoncontrollingInterest"],
        )
        long_term_debt = self._latest_instant(
            payload,
            as_of,
            concepts=["LongTermDebt", "LongTermDebtNoncurrent", "LongTermDebtAndFinanceLeaseObligationsNoncurrent"],
        )
        current_debt = self._latest_instant(
            payload,
            as_of,
            concepts=["LongTermDebtCurrent", "ShortTermBorrowings", "CommercialPaper"],
        )
        cash = self._latest_instant(payload, as_of, concepts=["CashAndCashEquivalentsAtCarryingValue"])

        latest_close = await self._latest_close_price(ticker, as_of_datetime)
        latest_shares = shares[0].value if shares else None
        market_cap = latest_close * latest_shares if latest_close is not None and latest_shares is not None else None
        total_debt = sum(item for item in [long_term_debt, current_debt] if item is not None) or None

        revenue_ttm = self._trailing_sum(revenues, periods=4)
        gross_profit_ttm = self._trailing_sum(gross_profit, periods=4)
        operating_income_ttm = self._trailing_sum(operating_income, periods=4)
        net_income_ttm = self._trailing_sum(net_income, periods=4)
        ocf_ttm = self._trailing_sum(operating_cash_flow, periods=4)
        capex_ttm = self._trailing_sum(capex, periods=4)
        depreciation_ttm = self._trailing_sum(depreciation, periods=4)
        dividend_ttm = self._trailing_sum(dividends_per_share, periods=4)

        enterprise_value = None
        if market_cap is not None:
            enterprise_value = market_cap + (total_debt or 0.0) - (cash or 0.0)

        ebitda_ttm = None
        if operating_income_ttm is not None and depreciation_ttm is not None:
            ebitda_ttm = operating_income_ttm + depreciation_ttm

        fcf_ttm = None
        if ocf_ttm is not None:
            fcf_ttm = ocf_ttm - abs(capex_ttm or 0.0)

        payload_out: dict[str, float | int | str | None] = {
            "company_name": company_name,
            "pe_ratio": self._safe_ratio(market_cap, net_income_ttm),
            "pb_ratio": self._safe_ratio(market_cap, equity),
            "ev_ebitda": self._safe_ratio(enterprise_value, ebitda_ttm),
            "gross_margin": self._safe_ratio(gross_profit_ttm, revenue_ttm),
            "operating_margin": self._safe_ratio(operating_income_ttm, revenue_ttm),
            "net_margin": self._safe_ratio(net_income_ttm, revenue_ttm),
            "roe": self._safe_ratio(net_income_ttm, equity),
            "roa": self._safe_ratio(net_income_ttm, assets),
            "debt_to_equity": self._safe_ratio(total_debt, equity),
            "current_ratio": self._safe_ratio(current_assets, liabilities_current),
            "forward_pe": None,
            "ev_revenue": self._safe_ratio(enterprise_value, revenue_ttm),
            "fcf_yield": self._safe_ratio(fcf_ttm, market_cap),
            "dividend_yield": self._safe_ratio(dividend_ttm, latest_close),
            "dividend_growth_years": self._dividend_growth_years(dividends_per_share),
            "buyback_ratio": self._buyback_ratio(shares),
            "revenue_growth_q1": self._quarterly_yoy(revenues, 0),
            "revenue_growth_q2": self._quarterly_yoy(revenues, 1),
            "revenue_growth_q3": self._quarterly_yoy(revenues, 2),
            "revenue_growth_q4": self._quarterly_yoy(revenues, 3),
            "earnings_growth_last4q": self._rolling_growth(net_income),
            "gross_margin_trend": self._gross_margin_trend(revenues, gross_profit),
        }
        return payload_out

    async def _latest_close_price(self, ticker: str, as_of_datetime: str | None) -> float | None:
        frame = await YFinanceAdapter().get_ohlcv(ticker, periods=5, as_of_datetime=as_of_datetime)
        closes = pd.to_numeric(frame.get("close"), errors="coerce").dropna()
        if closes.empty:
            return None
        return round(float(closes.iloc[-1]), 6)

    def _latest_instant(self, payload: dict[str, Any], as_of: date, *, concepts: list[str]) -> float | None:
        series = self._instant_series(payload, as_of, concepts=concepts, units={"USD"})
        return series[0].value if series else None

    def _instant_series(
        self,
        payload: dict[str, Any],
        as_of: date,
        *,
        concepts: list[str],
        units: set[str],
    ) -> list[FactPoint]:
        points = self._collect_points(payload, concepts=concepts, units=units, accepted_forms=INSTANT_FORMS)
        filtered = [point for point in points if point.filed <= as_of and point.end <= as_of]
        deduped = self._dedupe_by_end(filtered)
        return sorted(deduped, key=lambda point: (point.end, point.filed), reverse=True)

    def _quarterly_series(
        self,
        payload: dict[str, Any],
        as_of: date,
        *,
        concepts: list[str],
        units: set[str] | None = None,
    ) -> list[FactPoint]:
        points = self._collect_points(
            payload,
            concepts=concepts,
            units=units or {"USD"},
            accepted_forms=QUARTERLY_FORMS,
        )
        filtered = [
            point
            for point in points
            if point.filed <= as_of
            and point.end <= as_of
            and self._looks_quarterly(point)
        ]
        deduped = self._dedupe_by_end(filtered)
        return sorted(deduped, key=lambda point: (point.end, point.filed), reverse=True)

    def _collect_points(
        self,
        payload: dict[str, Any],
        *,
        concepts: list[str],
        units: set[str],
        accepted_forms: set[str],
    ) -> list[FactPoint]:
        facts = payload.get("facts", {})
        points: list[FactPoint] = []
        for taxonomy_name in ("us-gaap", "dei"):
            taxonomy = facts.get(taxonomy_name, {})
            if not isinstance(taxonomy, dict):
                continue
            for concept in concepts:
                concept_payload = taxonomy.get(concept, {})
                concept_units = concept_payload.get("units", {}) if isinstance(concept_payload, dict) else {}
                for unit_name, items in concept_units.items():
                    if unit_name not in units or not isinstance(items, list):
                        continue
                    for item in items:
                        try:
                            value = float(item.get("val"))
                            filed = datetime.fromisoformat(str(item.get("filed"))).date()
                            end = datetime.fromisoformat(str(item.get("end"))).date()
                        except (TypeError, ValueError):
                            continue
                        form = str(item.get("form", "")).upper()
                        if accepted_forms and form not in accepted_forms:
                            continue
                        start_raw = item.get("start")
                        start = None
                        if start_raw:
                            try:
                                start = datetime.fromisoformat(str(start_raw)).date()
                            except ValueError:
                                start = None
                        points.append(
                            FactPoint(
                                value=value,
                                filed=filed,
                                end=end,
                                start=start,
                                form=form,
                                fp=str(item.get("fp", "")).upper(),
                                frame=str(item.get("frame", "")).upper(),
                            )
                        )
        return points

    def _dedupe_by_end(self, points: list[FactPoint]) -> list[FactPoint]:
        latest: dict[date, FactPoint] = {}
        for point in points:
            current = latest.get(point.end)
            if current is None or point.filed > current.filed:
                latest[point.end] = point
        return list(latest.values())

    def _looks_quarterly(self, point: FactPoint) -> bool:
        if point.start is None:
            return "Q" in point.frame or point.fp.startswith("Q")
        duration = (point.end - point.start).days
        return duration <= 120 and ("Q" in point.frame or point.fp.startswith("Q") or point.form.startswith("10-Q"))

    def _trailing_sum(self, points: list[FactPoint], *, periods: int) -> float | None:
        if len(points) < periods:
            return None
        return round(sum(point.value for point in points[:periods]), 6)

    def _quarterly_yoy(self, points: list[FactPoint], offset: int) -> float | None:
        if len(points) <= offset + 4:
            return None
        previous = points[offset + 4].value
        current = points[offset].value
        return self._safe_growth(current, previous)

    def _rolling_growth(self, points: list[FactPoint]) -> float | None:
        current = self._trailing_sum(points, periods=4)
        previous = self._trailing_sum(points[4:], periods=4)
        return self._safe_growth(current, previous)

    def _gross_margin_trend(self, revenues: list[FactPoint], gross_profit: list[FactPoint]) -> float | None:
        if len(revenues) < 4 or len(gross_profit) < 4:
            return None
        recent = []
        prior = []
        revenue_map = {point.end: point.value for point in revenues}
        gross_map = {point.end: point.value for point in gross_profit}
        for end in [point.end for point in revenues[:4]]:
            revenue = revenue_map.get(end)
            gross = gross_map.get(end)
            if revenue in (None, 0) or gross is None:
                continue
            margin = gross / revenue
            if len(recent) < 2:
                recent.append(margin)
            else:
                prior.append(margin)
        if len(recent) < 2 or len(prior) < 2:
            return None
        return round((sum(recent) / len(recent)) - (sum(prior) / len(prior)), 6)

    def _buyback_ratio(self, shares: list[FactPoint]) -> float | None:
        if len(shares) < 2:
            return None
        latest = shares[0].value
        baseline = shares[4].value if len(shares) >= 5 else shares[-1].value
        if baseline <= 0:
            return None
        ratio = (baseline - latest) / baseline
        return round(max(0.0, ratio), 6)

    def _dividend_growth_years(self, dividends_per_share: list[FactPoint]) -> int | None:
        if not dividends_per_share:
            return None
        annual: dict[int, float] = {}
        for point in dividends_per_share:
            annual[point.end.year] = annual.get(point.end.year, 0.0) + point.value
        if not annual:
            return None
        count = 0
        previous: float | None = None
        for year in sorted(annual, reverse=True):
            numeric = float(annual[year])
            if numeric <= 0:
                break
            if previous is not None and numeric > previous:
                break
            previous = numeric
            count += 1
        return count

    def _safe_ratio(self, numerator: float | None, denominator: float | None) -> float | None:
        if numerator is None or denominator in (None, 0):
            return None
        if denominator < 0:
            return None
        return round(numerator / denominator, 6)

    def _safe_growth(self, current: float | None, previous: float | None) -> float | None:
        if current is None or previous in (None, 0):
            return None
        return round((current / previous) - 1.0, 6)
